### ISSUE TITLE
Windows Version Does not work 

### ISSUE THREAD

**Issue by shreeswifty** [SkAT-VG/SDT#18]
withdrawn

**Comment by stepap** [comment]
Do you use Pd i386? Currently only 32-bit is supported on Windows. That works just fine here.

**Comment by ChromaticIsobar** [comment]
Thanks for reporting this @shreeswifty .
As @stepap said, the distribution for windows is working on our systems.
Can you provide any info about your system, so that we can replicate this issue?
Helpful information would be:
   - the OS version
   - Pd version, bit-depth (32/64 bits) and distribution (e.g. extended, l2ork, purr-data)

**Comment by shreeswifty** [comment]
i apologize i was running the 64 bit exe. I've re-labelled and tested. Yes it works with the 32bit exe Windows10
sorry and thanks

**Comment by ChromaticIsobar** [comment]
Don't be sorry. This could be helpful for other people having the same issue.
Thank you
